<?php

namespace Plugin\FreeeLight\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FreeeAccountItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FreeeAccountItemRepository extends EntityRepository
{
}
