<?php

namespace Plugin\FreeeLight\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FreeeOAuth2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FreeeOAuth2Repository extends EntityRepository
{
}
